/*
 * This file is generated by jOOQ.
 */
package com.example.test.jooq.public_;


import com.example.test.jooq.public_.tables.Account;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;
}
